### ISSUE TITLE
Python class import and instantiation is different color from vs code theme 

### ISSUE THREAD

**Issue by testhej** [gmr458/vscode_modern_theme.nvim#6]
Hello, I was using the theme and noticed that when importing and instantiating classes they are light blue like normal variables whereas in vs code dark modern theme they are green.

Here is code from neovim using the your theme:
![image](https://github.com/gmr458/vscode_modern_theme.nvim/assets/120281524/31e3d375-d011-4562-964f-b444ae8a8ac7)

Here is the same code in vs code using the modern dark theme:
![image](https://github.com/gmr458/vscode_modern_theme.nvim/assets/120281524/e94e35c4-f19b-45f5-afc4-41bc3a273c46)

Not sure if this is intended behaviour or not but would be nice if classes could have the green color when they are imported and instantiated as well.

**Comment by gmr458** [comment]
I can change the color of the class when it is instantiated, but that would also change the color of the `__init__()` method because both `__init__()` and `n = Test()` use the hlgroup `@constructor`, at the time I chose yellow for constructors in Python because at the end of the day a constructor is a function and because for me the definition of the `__init__()` method being green does not look good.

Also I cannot change the color of the imported packages, this colorscheme uses treesitter and treesitter gives me the hlgroup `@variable` for packages. Treesitter can't know specifically what you import, I think it can only highlight something like a class if the name starts with a capital letter, that's because treesitter parses only the current file, but doesn't know anything about the rest of your project, that's when LSP comes in with semantic tokens

The thing is that the VSCode Python extension doesn't use pyright, it uses Pylance, a proprietary version of Pyright that has LSP semantic tokens, so Pylance knows if you are importing a package, a class, a function or a variable and the editor can use that for better highlights, if you deactivate the Python extension in VSCode you will be able to notice it.

There is a fork of pyright that supports semantic tokens called "basedpyright", I haven't used it so I can't tell you if it's any good.

**Comment by testhej** [comment]
I see, thanks for the response.
